site_name: Respeaker - Getting Started
theme: readthedocs
site_description: "Respeaker - Getting Started"
site_author: "Seed"
copyright: "Copyright © Seeedstudio 2016"
repo_url: https://github.com/d34dman/get_started_with_respeaker
edit_uri: blob/master/docs/
repo_name: GitHub
markdown_extensions:
  - admonition

pages:
    - index.md
    - 'Introduction' : Introduction.md
    - 'Quick Start' : QuickStart.md
    - 'Programming guide' : ProgrammingGuide.md
    - 'ReSpeaker Arduino Library' : ReSpeakerArduinoLibrary.md
    - 'ReSpeaker Python API' : ReSpeakerPythonAPI.md
